// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package simplejavaactions.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.io.InputStream;
import org.apache.commons.codec.digest.DigestUtils;

public class MD5CheckSum extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __fileDocument;
	private system.proxies.FileDocument fileDocument;

	public MD5CheckSum(IContext context, IMendixObject fileDocument)
	{
		super(context);
		this.__fileDocument = fileDocument;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.fileDocument = __fileDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), __fileDocument);

		// BEGIN USER CODE
		String md5 = null;
		try (InputStream is = Core.getFileDocumentContent(getContext(), fileDocument.getMendixObject())) {
			md5 = DigestUtils.md5Hex(is);
		}
		return md5;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MD5CheckSum";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
